language: node_js
node_js: stable
cache:
    apt: true
    directories:
        - node_modules
install:
    - npm install
before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - chmod +x ./bin/publish-to-gh-pages.sh
after_script:
    - ./bin/publish-to-gh-pages.sh
script:
    - hexo clean
    - hexo g
branches:
    only:
        - master
env:
    global:
        - GH_REF: github.com/dingziqi/blog-static.git