name: hexo

on:
  push:
    branches:
      - hexo2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: init
      uses: actions/checkout@v1

    - name: checkGit
      run: |
        git config user.name dingziqi
        git config user.email dingziqi_xtu@sina.com

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install

    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean

    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate

    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: dingziqi_xtu@sina.com
        NAME: dingziqi
      with:
        args: deploy
