name: hexo

on:
  push:
    branches:
      - hexo2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: init
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install

    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean

    - name: build and deploy
      run: |
        npx hexo clean
        npx hexo g
        npx hexo deploy

